[theme]
primaryColor = "#00ff41"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#262730"
textColor = "#fafafa"

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false
